### ISSUE TITLE
Hypnotoad chat feature not working

### ISSUE THREAD

**Issue by DDarkstorm** [BardMusicPlayer/DalamudDoot#13]
Hello,
I've done the install in the correct order and did it again but I can't get the "chat while performing" feature to work.
Other features like the "Direct Instrument open & close" do work so I don't know what makes this one not work.

Thanks for any help

**Comment by Meowchestra** [comment]
@DDarkstorm This was not yet implemented into BMP. It will be working as soon as this PR is merged.

https://github.com/BardMusicPlayer/BardMusicPlayer/pull/286

In the meantime you can double click on a performer and chat in the popup box, but hopefully won't be too long before made available.
